// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package com.example.authors

import java.util.UUID

data class Author (
  val authorId: Long,
  val ssid: Int?,
  val name: String,
  val spouses: Int?,
  val children: Int?,
  val bio: String,
  val acct: java.math.BigDecimal?
)

data class Book (
  val bookId: UUID,
  val name: String
)

