# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.18.0
import dataclasses
import decimal
from typing import Optional


@dataclasses.dataclass()
class Author:
    author_id: int
    ssid: Optional[int]
    name: str
    spouses: Optional[int]
    children: Optional[int]
    bio: str
    acct: Optional[decimal.Decimal]
