// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package com.example.authors

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement

const val deleteAuthor = """-- name: deleteAuthor :exec
DELETE FROM authors
WHERE author_id = ?
"""

const val insertAuthor = """-- name: insertAuthor :one
INSERT INTO authors
( 
    ssid
 ,  name
 ,  spouses
 ,  children
 ,  bio
 ,  acct
) VALUES (
    ?
 ,  ?
 ,  ?
 ,  ?
 ,  ?
 ,  ?
)
RETURNING author_id, ssid, name, spouses, children, bio, acct
"""

const val listAuthor = """-- name: listAuthor :many
SELECT author_id, ssid, name, spouses, children, bio, acct FROM authors
WHERE author_id > ?
ORDER BY author_id
LIMIT 1000
"""

const val selectAuthor = """-- name: selectAuthor :one
SELECT
    author_id
 ,  ssid
 ,  name
 ,  spouses
 ,  children
 ,  bio
 ,  acct
FROM authors
WHERE author_id = ?
"""

const val updateAuthor = """-- name: updateAuthor :one
UPDATE authors
SET 
    ssid = ?
 ,  name = ?
 ,  spouses = ?
 ,  children = ?
 ,  bio = ?
 ,  acct = ?
WHERE author_id = ?
RETURNING author_id, ssid, name, spouses, children, bio, acct
"""

class QueriesImpl(private val conn: Connection) : Queries {

// Delete one Author using author_id

  @Throws(SQLException::class)
  override fun deleteAuthor(authorId: Long) {
    conn.prepareStatement(deleteAuthor).use { stmt ->
      stmt.setLong(1, authorId)

      stmt.execute()
    }
  }

// Insert one row of Author

  @Throws(SQLException::class)
  override fun insertAuthor(
      ssid: Int?,
      name: String,
      spouses: Int?,
      children: Int?,
      bio: String,
      acct: java.math.BigDecimal?): Author? {
    return conn.prepareStatement(insertAuthor).use { stmt ->
      stmt.setInt(1, ssid)
          stmt.setString(2, name)
          stmt.setInt(3, spouses)
          stmt.setInt(4, children)
          stmt.setString(5, bio)
          stmt.setjava.math.BigDecimal(6, acct)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Author(
                results.getLong(1),
                results.getInt(2),
                results.getString(3),
                results.getInt(4),
                results.getInt(5),
                results.getString(6),
                results.getjava.math.BigDecimal(7)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

// Lists 1000 Author having id > @id

  @Throws(SQLException::class)
  override fun listAuthor(authorId: Long): List<Author> {
    return conn.prepareStatement(listAuthor).use { stmt ->
      stmt.setLong(1, authorId)

      val results = stmt.executeQuery()
      val ret = mutableListOf<Author>()
      while (results.next()) {
          ret.add(Author(
                results.getLong(1),
                results.getInt(2),
                results.getString(3),
                results.getInt(4),
                results.getInt(5),
                results.getString(6),
                results.getjava.math.BigDecimal(7)
            ))
      }
      ret
    }
  }

// Select one Author using author_id

  @Throws(SQLException::class)
  override fun selectAuthor(authorId: Long): Author? {
    return conn.prepareStatement(selectAuthor).use { stmt ->
      stmt.setLong(1, authorId)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Author(
                results.getLong(1),
                results.getInt(2),
                results.getString(3),
                results.getInt(4),
                results.getInt(5),
                results.getString(6),
                results.getjava.math.BigDecimal(7)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

// Update one row of Author using author_id

  @Throws(SQLException::class)
  override fun updateAuthor(
      ssid: Int?,
      name: String,
      spouses: Int?,
      children: Int?,
      bio: String,
      acct: java.math.BigDecimal?,
      authorId: Long): Author? {
    return conn.prepareStatement(updateAuthor).use { stmt ->
      stmt.setInt(1, ssid)
          stmt.setString(2, name)
          stmt.setInt(3, spouses)
          stmt.setInt(4, children)
          stmt.setString(5, bio)
          stmt.setjava.math.BigDecimal(6, acct)
          stmt.setLong(7, authorId)

      val results = stmt.executeQuery()
      if (!results.next()) {
        return null
      }
      val ret = Author(
                results.getLong(1),
                results.getInt(2),
                results.getString(3),
                results.getInt(4),
                results.getInt(5),
                results.getString(6),
                results.getjava.math.BigDecimal(7)
            )
      if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
      }
      ret
    }
  }

}

