// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package authors

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	AuthorID int64
	Ssid     sql.NullInt32
	Name     string
	Spouses  sql.NullInt32
	Children sql.NullInt32
	Bio      string
	Acct     sql.NullString
}

type Book struct {
	BookID uuid.UUID
	Name   string
}
