// Code generated by qtc from "mysql.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line mysql.qtpl:1
package templates

//line mysql.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-crud/internal/core"
)

//line mysql.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mysql.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mysql.qtpl:6
func StreamMysql(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line mysql.qtpl:6
	qw422016.N().S(`
`)
//line mysql.qtpl:7
	for _, r := range ctx.DataClasses {
//line mysql.qtpl:7
		qw422016.N().S(`

`)
//line mysql.qtpl:10
		id := getIdField(r.Name, r.Fields)
		idIsInt := keyIsInt(r.Name, r.Fields)

//line mysql.qtpl:12
		qw422016.N().S(`

-- name: Select`)
//line mysql.qtpl:14
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:14
		qw422016.N().S(` :one
-- Select one `)
//line mysql.qtpl:15
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:15
		qw422016.N().S(` using `)
//line mysql.qtpl:15
		qw422016.E().S(id)
//line mysql.qtpl:15
		qw422016.N().S(`
SELECT
`)
//line mysql.qtpl:17
		for idx, f := range r.Fields {
//line mysql.qtpl:18
			if idx != 0 {
//line mysql.qtpl:18
				qw422016.N().S(` , `)
//line mysql.qtpl:18
			} else {
//line mysql.qtpl:18
				qw422016.N().S(`   `)
//line mysql.qtpl:18
			}
//line mysql.qtpl:18
			qw422016.N().S(` `)
//line mysql.qtpl:18
			qw422016.E().S(f.Name)
//line mysql.qtpl:18
			qw422016.N().S(`
`)
//line mysql.qtpl:19
		}
//line mysql.qtpl:19
		qw422016.N().S(`FROM `)
//line mysql.qtpl:20
		qw422016.E().S(r.Table.Name)
//line mysql.qtpl:20
		qw422016.N().S(`
WHERE `)
//line mysql.qtpl:21
		qw422016.E().S(id)
//line mysql.qtpl:21
		qw422016.N().S(` = ? ;

-- name: Delete`)
//line mysql.qtpl:23
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:23
		qw422016.N().S(` :exec
-- Delete one `)
//line mysql.qtpl:24
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:24
		qw422016.N().S(` using `)
//line mysql.qtpl:24
		qw422016.E().S(id)
//line mysql.qtpl:24
		qw422016.N().S(`
DELETE FROM `)
//line mysql.qtpl:25
		qw422016.E().S(r.Table.Name)
//line mysql.qtpl:25
		qw422016.N().S(`
WHERE `)
//line mysql.qtpl:26
		qw422016.E().S(id)
//line mysql.qtpl:26
		qw422016.N().S(` = ? ;

-- name: Update`)
//line mysql.qtpl:28
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:28
		qw422016.N().S(` :exec
-- Update one row of `)
//line mysql.qtpl:29
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:29
		qw422016.N().S(` using `)
//line mysql.qtpl:29
		qw422016.E().S(id)
//line mysql.qtpl:29
		qw422016.N().S(`
UPDATE `)
//line mysql.qtpl:30
		qw422016.E().S(r.Table.Name)
//line mysql.qtpl:30
		qw422016.N().S(`
SET 
`)
//line mysql.qtpl:32
		for idx, f := range skipIdField(id, r.Fields) {
//line mysql.qtpl:33
			if idx != 0 {
//line mysql.qtpl:33
				qw422016.N().S(` , `)
//line mysql.qtpl:33
			} else {
//line mysql.qtpl:33
				qw422016.N().S(`   `)
//line mysql.qtpl:33
			}
//line mysql.qtpl:33
			qw422016.N().S(` `)
//line mysql.qtpl:33
			qw422016.E().S(f.Name)
//line mysql.qtpl:33
			qw422016.N().S(` = ?
`)
//line mysql.qtpl:34
		}
//line mysql.qtpl:34
		qw422016.N().S(`WHERE `)
//line mysql.qtpl:35
		qw422016.E().S(id)
//line mysql.qtpl:35
		qw422016.N().S(` = ? ;

-- name: Insert`)
//line mysql.qtpl:37
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:37
		qw422016.N().S(` :execresult
-- Insert one row of `)
//line mysql.qtpl:38
		qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:38
		qw422016.N().S(`
INSERT INTO `)
//line mysql.qtpl:39
		qw422016.E().S(r.Table.Name)
//line mysql.qtpl:39
		qw422016.N().S(`
( 
`)
//line mysql.qtpl:41
		for idx, f := range skipIdField(id, r.Fields) {
//line mysql.qtpl:42
			if idx != 0 {
//line mysql.qtpl:42
				qw422016.N().S(` , `)
//line mysql.qtpl:42
			} else {
//line mysql.qtpl:42
				qw422016.N().S(`   `)
//line mysql.qtpl:42
			}
//line mysql.qtpl:42
			qw422016.N().S(` `)
//line mysql.qtpl:42
			qw422016.E().S(f.Name)
//line mysql.qtpl:42
			qw422016.N().S(`
`)
//line mysql.qtpl:43
		}
//line mysql.qtpl:43
		qw422016.N().S(`) VALUES (
`)
//line mysql.qtpl:45
		for idx, _ := range skipIdField(id, r.Fields) {
//line mysql.qtpl:46
			if idx != 0 {
//line mysql.qtpl:46
				qw422016.N().S(` , `)
//line mysql.qtpl:46
			} else {
//line mysql.qtpl:46
				qw422016.N().S(`   `)
//line mysql.qtpl:46
			}
//line mysql.qtpl:46
			qw422016.N().S(` ?
`)
//line mysql.qtpl:47
		}
//line mysql.qtpl:47
		qw422016.N().S(`) ;

`)
//line mysql.qtpl:50
		if idIsInt {
//line mysql.qtpl:50
			qw422016.N().S(` 
-- name: List`)
//line mysql.qtpl:51
			qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:51
			qw422016.N().S(` :many
-- Lists 1000 `)
//line mysql.qtpl:52
			qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:52
			qw422016.N().S(` having id > ?
SELECT * FROM `)
//line mysql.qtpl:53
			qw422016.E().S(r.Table.Name)
//line mysql.qtpl:53
			qw422016.N().S(`
WHERE `)
//line mysql.qtpl:54
			qw422016.E().S(id)
//line mysql.qtpl:54
			qw422016.N().S(` > ?
ORDER BY `)
//line mysql.qtpl:55
			qw422016.E().S(id)
//line mysql.qtpl:55
			qw422016.N().S(`
LIMIT 1000 ;
`)
//line mysql.qtpl:57
		} else {
//line mysql.qtpl:57
			qw422016.N().S(`
-- name: List`)
//line mysql.qtpl:58
			qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:58
			qw422016.N().S(` :many
-- Lists all `)
//line mysql.qtpl:59
			qw422016.E().S(toTitle(r.Name))
//line mysql.qtpl:59
			qw422016.N().S(` 
SELECT * FROM `)
//line mysql.qtpl:60
			qw422016.E().S(r.Table.Name)
//line mysql.qtpl:60
			qw422016.N().S(`
ORDER BY `)
//line mysql.qtpl:61
			qw422016.E().S(id)
//line mysql.qtpl:61
			qw422016.N().S(`
`)
//line mysql.qtpl:62
		}
//line mysql.qtpl:62
		qw422016.N().S(`

`)
//line mysql.qtpl:64
	}
//line mysql.qtpl:64
	qw422016.N().S(`

`)
//line mysql.qtpl:66
}

//line mysql.qtpl:66
func WriteMysql(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line mysql.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mysql.qtpl:66
	StreamMysql(qw422016, ctx)
//line mysql.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line mysql.qtpl:66
}

//line mysql.qtpl:66
func Mysql(ctx core.TmplCtx) string {
//line mysql.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line mysql.qtpl:66
	WriteMysql(qb422016, ctx)
//line mysql.qtpl:66
	qs422016 := string(qb422016.B)
//line mysql.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line mysql.qtpl:66
	return qs422016
//line mysql.qtpl:66
}
