// Code generated by qtc from "pg.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pg.qtpl:1
package templates

//line pg.qtpl:1
import (
	"github.com/kaashyapan/sqlc-gen-crud/internal/core"
)

//line pg.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pg.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pg.qtpl:8
func StreamPg(qw422016 *qt422016.Writer, ctx core.TmplCtx) {
//line pg.qtpl:8
	qw422016.N().S(`
`)
//line pg.qtpl:9
	for _, r := range ctx.DataClasses {
//line pg.qtpl:9
		qw422016.N().S(`

`)
//line pg.qtpl:12
		id := getIdField(r.Name, r.Fields)
		idIsInt := keyIsInt(r.Name, r.Fields)

//line pg.qtpl:14
		qw422016.N().S(`

-- name: Select`)
//line pg.qtpl:16
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:16
		qw422016.N().S(` :one
-- Select one `)
//line pg.qtpl:17
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:17
		qw422016.N().S(` using `)
//line pg.qtpl:17
		qw422016.E().S(id)
//line pg.qtpl:17
		qw422016.N().S(`
SELECT
`)
//line pg.qtpl:19
		for idx, f := range r.Fields {
//line pg.qtpl:20
			if idx != 0 {
//line pg.qtpl:20
				qw422016.N().S(` , `)
//line pg.qtpl:20
			} else {
//line pg.qtpl:20
				qw422016.N().S(`   `)
//line pg.qtpl:20
			}
//line pg.qtpl:20
			qw422016.N().S(` `)
//line pg.qtpl:20
			qw422016.E().S(f.Name)
//line pg.qtpl:20
			qw422016.N().S(`
`)
//line pg.qtpl:21
		}
//line pg.qtpl:21
		qw422016.N().S(`FROM `)
//line pg.qtpl:22
		qw422016.E().S(r.Table.Name)
//line pg.qtpl:22
		qw422016.N().S(`
WHERE `)
//line pg.qtpl:23
		qw422016.E().S(id)
//line pg.qtpl:23
		qw422016.N().S(` = @`)
//line pg.qtpl:23
		qw422016.E().S(id)
//line pg.qtpl:23
		qw422016.N().S(` ;

-- name: Delete`)
//line pg.qtpl:25
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:25
		qw422016.N().S(` :exec
-- Delete one `)
//line pg.qtpl:26
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:26
		qw422016.N().S(` using `)
//line pg.qtpl:26
		qw422016.E().S(id)
//line pg.qtpl:26
		qw422016.N().S(`
DELETE FROM `)
//line pg.qtpl:27
		qw422016.E().S(r.Table.Name)
//line pg.qtpl:27
		qw422016.N().S(`
WHERE `)
//line pg.qtpl:28
		qw422016.E().S(id)
//line pg.qtpl:28
		qw422016.N().S(` = @`)
//line pg.qtpl:28
		qw422016.E().S(id)
//line pg.qtpl:28
		qw422016.N().S(` ;

-- name: Update`)
//line pg.qtpl:30
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:30
		qw422016.N().S(` :one
-- Update one row of `)
//line pg.qtpl:31
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:31
		qw422016.N().S(` using `)
//line pg.qtpl:31
		qw422016.E().S(id)
//line pg.qtpl:31
		qw422016.N().S(`
UPDATE `)
//line pg.qtpl:32
		qw422016.E().S(r.Table.Name)
//line pg.qtpl:32
		qw422016.N().S(`
SET 
`)
//line pg.qtpl:34
		for idx, f := range skipIdField(id, r.Fields) {
//line pg.qtpl:35
			if idx != 0 {
//line pg.qtpl:35
				qw422016.N().S(` , `)
//line pg.qtpl:35
			} else {
//line pg.qtpl:35
				qw422016.N().S(`   `)
//line pg.qtpl:35
			}
//line pg.qtpl:35
			qw422016.N().S(` `)
//line pg.qtpl:35
			qw422016.E().S(f.Name)
//line pg.qtpl:35
			qw422016.N().S(` = @`)
//line pg.qtpl:35
			qw422016.E().S(f.Name)
//line pg.qtpl:35
			qw422016.N().S(`
`)
//line pg.qtpl:36
		}
//line pg.qtpl:36
		qw422016.N().S(`WHERE `)
//line pg.qtpl:37
		qw422016.E().S(id)
//line pg.qtpl:37
		qw422016.N().S(` = @`)
//line pg.qtpl:37
		qw422016.E().S(id)
//line pg.qtpl:37
		qw422016.N().S(`
RETURNING * ;

-- name: Insert`)
//line pg.qtpl:40
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:40
		qw422016.N().S(` :one
-- Insert one row of `)
//line pg.qtpl:41
		qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:41
		qw422016.N().S(`
INSERT INTO `)
//line pg.qtpl:42
		qw422016.E().S(r.Table.Name)
//line pg.qtpl:42
		qw422016.N().S(`
( 
`)
//line pg.qtpl:44
		for idx, f := range skipIdField(id, r.Fields) {
//line pg.qtpl:45
			if idx != 0 {
//line pg.qtpl:45
				qw422016.N().S(` , `)
//line pg.qtpl:45
			} else {
//line pg.qtpl:45
				qw422016.N().S(`   `)
//line pg.qtpl:45
			}
//line pg.qtpl:45
			qw422016.N().S(` `)
//line pg.qtpl:45
			qw422016.E().S(f.Name)
//line pg.qtpl:45
			qw422016.N().S(`
`)
//line pg.qtpl:46
		}
//line pg.qtpl:46
		qw422016.N().S(`) VALUES (
`)
//line pg.qtpl:48
		for idx, f := range skipIdField(id, r.Fields) {
//line pg.qtpl:49
			if idx != 0 {
//line pg.qtpl:49
				qw422016.N().S(` , `)
//line pg.qtpl:49
			} else {
//line pg.qtpl:49
				qw422016.N().S(`   `)
//line pg.qtpl:49
			}
//line pg.qtpl:49
			qw422016.N().S(` @`)
//line pg.qtpl:49
			qw422016.E().S(f.Name)
//line pg.qtpl:49
			qw422016.N().S(`
`)
//line pg.qtpl:50
		}
//line pg.qtpl:50
		qw422016.N().S(`)
RETURNING * ;

`)
//line pg.qtpl:54
		if idIsInt {
//line pg.qtpl:54
			qw422016.N().S(` 
-- name: List`)
//line pg.qtpl:55
			qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:55
			qw422016.N().S(` :many
-- Lists 1000 `)
//line pg.qtpl:56
			qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:56
			qw422016.N().S(` having id > ?
SELECT * FROM `)
//line pg.qtpl:57
			qw422016.E().S(r.Table.Name)
//line pg.qtpl:57
			qw422016.N().S(`
WHERE `)
//line pg.qtpl:58
			qw422016.E().S(id)
//line pg.qtpl:58
			qw422016.N().S(` > @`)
//line pg.qtpl:58
			qw422016.E().S(id)
//line pg.qtpl:58
			qw422016.N().S(`
ORDER BY `)
//line pg.qtpl:59
			qw422016.E().S(id)
//line pg.qtpl:59
			qw422016.N().S(`
LIMIT 1000 ;
`)
//line pg.qtpl:61
		} else {
//line pg.qtpl:61
			qw422016.N().S(`
-- name: List`)
//line pg.qtpl:62
			qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:62
			qw422016.N().S(` :many
-- Lists all `)
//line pg.qtpl:63
			qw422016.E().S(toTitle(r.Name))
//line pg.qtpl:63
			qw422016.N().S(` 
SELECT * FROM `)
//line pg.qtpl:64
			qw422016.E().S(r.Table.Name)
//line pg.qtpl:64
			qw422016.N().S(`
ORDER BY `)
//line pg.qtpl:65
			qw422016.E().S(id)
//line pg.qtpl:65
			qw422016.N().S(`
`)
//line pg.qtpl:66
		}
//line pg.qtpl:66
		qw422016.N().S(`

`)
//line pg.qtpl:68
	}
//line pg.qtpl:68
	qw422016.N().S(`

`)
//line pg.qtpl:70
}

//line pg.qtpl:70
func WritePg(qq422016 qtio422016.Writer, ctx core.TmplCtx) {
//line pg.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pg.qtpl:70
	StreamPg(qw422016, ctx)
//line pg.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line pg.qtpl:70
}

//line pg.qtpl:70
func Pg(ctx core.TmplCtx) string {
//line pg.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line pg.qtpl:70
	WritePg(qb422016, ctx)
//line pg.qtpl:70
	qs422016 := string(qb422016.B)
//line pg.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line pg.qtpl:70
	return qs422016
//line pg.qtpl:70
}
