// Code generated by sqlc. DO NOT EDIT.
// version: sqlc v1.18.0
// for nuget package Npgsql.FSharp --version 5.7.0

namespace PAuthors

open System
open Npgsql
open Npgsql.FSharp

module Readers =

    let authorReader (r: RowReader) : Author = { Author.AuthorId = r.int64 "author_id" ; Ssid = r.intOrNone "ssid" ; Name = r.string "name" ; Spouses = r.intOrNone "spouses" ; Children = r.intOrNone "children" ; Bio = r.string "bio" ; Acct = r.decimalOrNone "acct" }

    let bookReader (r: RowReader) : Book = { Book.BookId = r.uuid "book_id" ; Name = r.string "name" }

